supplement:
  details: >
    product information, purpose and claim, effectiveness,
    ingredients, side effects, value for money and 
    customer reviews

book:
  details: >
    book information, summary, effectiveness, critique,
    audience, educational value, impact,
    value for money and customer reviews

deliverable:
  details: >
    information, purpose, effectiveness, features, benefits,
    value for money, and customer reviews