product_researcher_task:
  description: >
    The task of the Product Researcher is to use search tools to gather and analyze information related to {topic}. 
    This includes {details}.
    Treat {topic} as a single keyword
  expected_output: >
    A comprehensive report detailing the findings from the research. 
    This report should include information about unique features and benefits of the product.

keyword_researcher_task:
  description: >
    The task of the Keyword Researcher is to identify and analyze relevant keywords for SEO optimization and content creation for {topic}.
    Treat {topic} as a single keyword
  expected_output: >
    A list of relevant keywords that can be used for SEO optimization and content creation. 
    This list should include keywords that are relevant to {topic} and have high search volume.

review_drafter_task:
  description: >
    The task of the Review Drafter is to create a compelling and persuasive review for {topic} 
    using the information gathered and the keywords identified by the Keyword Researcher. 
    The review should be engaging, informative, and make effective use of the provided keywords.
    The review should always be written in the third person.
    The review should only discuss about the product reviewed and never discuss about other staffs.
  expected_output: >
    A well-written review that effectively incorporates the provided keywords and information about the product. 
    The review should be persuasive and highlight the unique features and benefits of the product.
    The length of the final draft should be more than 800 words.
    Never mention the author or the publisher in the review, even if you know the author name.
    Each paragraph may only contain maximum of 3 sentences.
    First sentence of the final draft is the title of the review.
    The title must be between 60 to 70 characters.

draft_critique_task:
  description: >
    The task of the Draft Critique is to provide a critical review of the draft produced by the Review Drafter. 
    The critique should assess the persuasiveness of the review, the effective use of keywords, and the accuracy of the product information.
    It should also ensure that aspects with no information are not mentioned in the review.
    The critique should confirm that the review is written in the third person and does not mention the review process.
  expected_output: >
    A detailed critique of the review draft. 
    The critique should highlight areas of the draft that are well done and suggest improvements where necessary.

final_drafter_task:
  description: >
    The task of the Final Drafter is to revise the draft produced by the Review Drafter based on the critique provided by the Draft Critique. 
    The Final Drafter should not repeat the critique verbatim, but rather use it as guidance to improve the draft.
    The Final Drafter should address all the points raised in the critique, ensuring that the review is persuasive, makes effective use of keywords, and accurately represents the product information.
    The Final Drafter should also ensure that aspects with no information are not mentioned in the review, that the review is written in the third person, and that the review process is not discussed.
    The revised review should maintain a length of more than 800 words, with each paragraph containing a maximum of 3 sentences.
    The first sentence of the final draft should be the title of the review, which must be between 60 to 70 characters.
  expected_output: >
    A revised review that addresses all the points raised in the critique without repeating the critique verbatim. 
    The review should be persuasive, effectively incorporate the provided keywords, and accurately represent the product information.
    The review should not mention aspects with no information, should be written in the third person, and should not discuss the review process.
    The length of the final draft should be more than 800 words, with each paragraph containing a maximum of 3 sentences.
    The first sentence of the final draft should be the title of the review, which must be between 60 to 70 characters.

problem_identifier_task:
  description: >
    Research the product {topic} to understand the main problem or disease it solves.
  expected_output: >
    list of problems or diseases the product {topic} solves.

problem_keyword_researcher_task:
  description: >
    The task of the Problem Keyword Researcher is to identify and analyze relevant keywords for SEO optimization and content creation based on the main problem or disease identified by the Problem Identifier. 
    The Problem Keyword Researcher should use their expertise in keyword research and SEO to find keywords that are relevant, have high search volume, and low competition.
  expected_output: >
    A list of relevant keywords for SEO optimization and content creation. 
    Each keyword should be relevant to the main problems or diseases listed by previous agent, have high search volume, and low competition.

problem_expert_task:
  description: >
    The task of the Problem Expert is to write an 800-word article using the first top most searched keyword found by the problem_keyword_researcher. 
    The article should be informative, engaging, and incorporate the keywords in a natural and meaningful way.
    Only use information from the previous agents, and never create new information.
  expected_output: >
    An 800-word of a narative article that effectively incorporates the top most searched keyword.
    Always use serper_dev_tool to find information about the keyword. Never fabricate information. 
    The article should be engaging, informative, and written in a way that naturally includes the keywords. 
    The article should be written in the third person and be persuasive, subtly highlighting how understanding the problem can lead to solutions.
    The length of the final draft should be exactly 800 words.
    The article only contain paragraphs that are informative and engaging, never put any sections.
    Each paragraph may only contain maximum of 3 sentences.
    First sentence of the final draft is the title of the review.
    The title must be between 60 to 70 characters.
    Mention product {topic} only in the last paragraph, using information found by keyword_researcher_task.