product_researcher_task:
  description: >
    The task of the Product Researcher is to use search tools to gather and analyze information related to {topic}. 
    This includes {details}.
    Treat {topic} as a single keyword
  expected_output: >
    A comprehensive report detailing the findings from the research. 
    This report should include information about unique features and benefits of the product.

keyword_researcher_task:
  description: >
    The task of the Keyword Researcher is to identify and analyze relevant keywords for SEO optimization and content creation for {topic}.
    Treat {topic} as a single keyword
  expected_output: >
    A list of relevant keywords that can be used for SEO optimization and content creation. 
    This list should include keywords that are relevant to {topic} and have high search volume.

review_drafter_task:
  description: >
    The task of the Review Drafter is to create a compelling and persuasive review for {topic} 
    using the information gathered and the keywords identified by the Keyword Researcher. 
    The review should be engaging, informative, and make effective use of the provided keywords.
    The review should always be written in the third person.
    The review should only discuss about the product reviewed and never discuss about other staffs.
  expected_output: >
    A well-written review that effectively incorporates the provided keywords and information about the product. 
    The review should be persuasive and highlight the unique features and benefits of the product.
    The length of the final draft should be more than 2500 words.
    Never mention the author or the publisher in the review, even if you know the author name.
    Each paragraph may only contain maximum of 3 sentences.
    First sentence of the final draft is the title of the review.
    The title must be between 60 to 70 characters.

draft_critique_task:
  description: >
    The task of the Draft Critique is to provide a critical review of the draft produced by the Review Drafter. 
    The critique should assess the persuasiveness of the review, the effective use of keywords, and the accuracy of the product information.
    It should also ensure that aspects with no information are not mentioned in the review.
    The critique should confirm that the review is written in the third person and does not mention the review process.
  expected_output: >
    A detailed critique of the review draft. 
    The critique should highlight areas of the draft that are well done and suggest improvements where necessary.

final_drafter_task:
  description: >
    The task of the Final Drafter is to revise the draft produced by the Review Drafter based on the critique provided by the Draft Critique. 
    The Final Drafter should not repeat the critique verbatim, but rather use it as guidance to improve the draft.
    The Final Drafter should address all the points raised in the critique, ensuring that the review is persuasive, makes effective use of keywords, and accurately represents the product information.
    The Final Drafter should also ensure that aspects with no information are not mentioned in the review, that the review is written in the third person, and that the review process is not discussed.
    The revised review should maintain a length of more than 2500 words, with each paragraph containing a maximum of 3 sentences.
    The first sentence of the final draft should be the title of the review, which must be between 60 to 70 characters.
  expected_output: >
    A revised review that addresses all the points raised in the critique without repeating the critique verbatim. 
    The review should be persuasive, effectively incorporate the provided keywords, and accurately represent the product information.
    The review should not mention aspects with no information, should be written in the third person, and should not discuss the review process.
    The length of the final draft should be more than 2500 words, with each paragraph containing a maximum of 3 sentences.
    The first sentence of the final draft should be the title of the review, which must be between 60 to 70 characters.

problem_identifier_task:
  description: >
    Research the product {topic} that has the following details {product_detail} to understand the main problem or disease related to the product.
  expected_output: >
    list of problems or diseases the product {topic} solves.

# problem_identifier_task:
#   description: >
#     Research the problem or disease related to the product being discussed. This involves understanding the main problem or disease that the product is designed to address or alleviate.
#   expected_output: >
#     A list of problems or diseases that the discussed product is designed to address or alleviate.

problem_keyword_researcher_task:
  description: >
    The task of the Problem Keyword Researcher is to identify and analyze relevant keywords for SEO optimization and content creation based on the main problem or disease identified by the Problem Identifier. 
    The Problem Keyword Researcher should use their expertise in keyword research and SEO to find keywords that are relevant, have high search volume, and low competition.
  expected_output: >
    A list of relevant keywords for SEO optimization and content creation. 
    Each keyword should be relevant to the main problems or diseases listed by previous agent, have high search volume, and low competition.
    Never include the product {topic} in the keywords.

problem_expert_task:
  description: >
    The Problem Expert's task is to write an 2500-word article using the top keyword found by the problem_keyword_researcher. 
    The article should be informative, engaging, and naturally incorporate the keyword, written using third person perspective.
    Information from previous agents should be used exclusively.
    The article should be formatted as a list of numbered points.
  expected_output: >
    An 2500-word narrative article incorporating the top keyword, formatted as a list of numbered points. 
    Always use serper_dev_tool to find information about the keyword. Never fabricate information. 
    The article should be engaging, informative, and subtly highlight how understanding the problem can lead to solutions. 
    The article should contain 5 to 9 informative and engaging points. Each point should be between 3 to 5 words long.
    Each point in the article should be explained in detail.
    The first sentence of the final draft, which is the title, should be between 60 to 70 characters, mention the number of points in the article (e.g. "5 Key Strategies to...", "Get More Power with these 5 tips..."), and be engaging, informative, and provoke curiosity. 
    The product {topic} should be mentioned only in the last point, using information found by the keyword_researcher_task.
    The output should only contain the article content and no additional notes or outputs.


article_expander_task:
  description: >
    The task of the Article Expander is to check if the length of the article has more than 2500 words.
    If the article is less than 2500 words, expand it until it is more than 2500 words. 
    The expansion should maintain the original focus of the article and incorporate additional relevant information.
  expected_output: >
    An article that is more than 2500 words long, starting with an engaging introduction paragraph, and maintaining the original focus while incorporating additional relevant information. 
    The expanded article should still be engaging, informative, and subtly highlight how understanding the problem can lead to solutions. 
    The expanded article should contain more than 5 to 9 informative and engaging points, each point is explained by more than 200 words long paragraph(s). 
    Always use serper_dev_tool to find information about the points in the article. Never fabricate information. 
    The first sentence of the final draft, which is the title, should still be between 60 to 70 characters, mention the number of points in the article (e.g. "7 Key Strategies to...", "Get More Power with these 10 tips..."), and be engaging, informative, and provoke curiosity. 
    The product {topic} should be mentioned only in the last point, using information found by the keyword_researcher_task.
    Relate the article with product {topic} for smooth introduction of the product.
    The output should only contain the expanded article content and no additional notes or outputs.


final_formatter_task:
  description: >
    The task of the Final Formatter is to take the expanded article produced by the Article Expander and apply final formatting. 
    The formatting should include marking each numbered item with an <h2> tag for better readability and SEO optimization. 
    The title of the article should not be marked with any HTML tag.
  expected_output: >
    A final version of the expanded article with each numbered item (excluding the title) marked with an <h2> tag. 
    The final article should still be engaging, informative, and subtly highlight how understanding the problem can lead to solutions. 
    The first sentence of the final draft, which is the title, should still be between 60 to 70 characters, mention the number of points in the article (e.g. "7 Key Strategies to...", "Get More Power with these 10 tips..."), and be engaging, informative, and provoke curiosity. 
    The product {topic} should be mentioned only in the last point, using information found by the keyword_researcher_task.
    The output should only contain the final formatted article content and no additional notes or outputs.
    Add an introduction paragraph at the beginning of the article without mentioning "Introduction:". 
    The introduction should set the context for the rest of the article and engage the reader's interest.
    Ensure that the article has an engaging title that is between 60 to 70 characters long and accurately reflects the content of the article.
    If {topic} is mentioned in the title, remove it and replace it with a more engaging term. 

journal_reader_task:
  description: >
    The task of the Journal Reader is to retrieve information related to {item} from academic journals available at https://www.ncbi.nlm.nih.gov/.
    The Journal Reader should use their skills in web scraping and information retrieval to extract the most relevant and up-to-date information about the {item}.
  expected_output: >
    A detailed summary or report containing the most relevant and up-to-date related information about {item} from academic journals available at https://www.ncbi.nlm.nih.gov/.
    The output should be in a format that can be easily understood and used by other agents or tasks.
    All outputs must be from the real journal. If no journal is found, mention that no journal is available.
    Never fabricate any information.

text_rewriting_task:
  description: >
    The task of the Text Rewriter is to take the final text produced by the previous tasks and rewrite it to improve its cohesion and coherence, while maintaining the original format.
    The Text Rewriter should use their skills in language and text processing to enhance the readability and flow of the text, ensuring that the ideas and arguments are logically connected and easy to follow.
  expected_output: >
    A rewritten version of the final text that is more cohesive and coherent, but still maintains the original format.
    The rewritten text should still be engaging, informative, and subtly highlight how understanding the problem can lead to solutions. 
    The first sentence of the final draft, which is the title, should still be between 60 to 70 characters, mention the number of points in the article (e.g. "7 Key Strategies to...", "Get More Power with these 10 tips..."), and be engaging, informative, and provoke curiosity. 
    The product {topic} should be mentioned only in the last point, using information found by the keyword_researcher_task.
    The output should only contain the rewritten article content and no additional notes or outputs.

article_writing_task:
  description: >
    The task of the Article Writer is to create an article about a specific {topic} using a defined format.
    The Article Writer should use their skills in content creation and formatting to write an engaging and informative article.
    The article should maintain a logical flow, be coherent, and subtly highlight how understanding the problem can lead to solutions.
    The first sentence of the article, which is the title, should be between 60 to 70 characters, mention the number of points in the article (e.g. "7 Key Strategies to...", "Get More Power with these 10 tips..."), and be engaging, informative, and provoke curiosity.
    The product {topic} should be mentioned only in the last point, using information found by the keyword_researcher_task.
  expected_output: >
    An article that follows the defined format and is about the specific {topic}.
    The article should be engaging, informative, and subtly highlight how understanding the problem can lead to solutions.
    The format of the article must be as follows:
      - Title: 60 to 70 characters, engaging, informative, and provoking curiosity.
      - Introduction: Engaging and informative introduction to the topic.
      - <H2>Point</H2>: Engaging and informative content.
      - <p>Content</p>: one paragraph of the detailed explanation of the Point. Never mention the {topic} in the content. Always use serper_dev_tool to find information about the point. Never fabricate information.
      - ... (Point, Content, Content format may be repeated for N times - maximum 5 points)
    Finally, mention the product {topic} in the last point, using information found by the keyword_researcher_task.


explanation_provider_task:
  description: >
    The task of the Explanation Provider is provide a detailed explanation on {item}, based on the information from other agent.
    The explanation should have 2 paragraphs and be at 6 sentences long, making the article informative and engaging.
  expected_output: >
    Detailed explanations for {item}, based on the information from other agent. 
    The explanation must have 2 paragraphs and be at least 6 sentences long, making the explanation informative and engaging. 
    Always use serper_dev_tool to find facts. Never fabricate any information. 
    The explanations should subtly highlight how understanding the problem can lead to solutions. 
    The output should only contain the explanations and no additional notes or outputs.
    Never mention about the {item} in the explanation.
    Never conclude the explanation.